### ISSUE TITLE
async method won't finish if proxy get's out of scope

### ISSUE THREAD

**Issue by hellow554** [Kistler-Group/sdbus-cpp#140] opened 2021-01-27 11:47 UTC
The following code doesn't print "The callback is done!";

```
#include <iostream>
#include <sdbus-c++/sdbus-c++.h>

auto get_proxy() {
  return sdbus::createProxy("org.freedesktop.timedate1",
                            "/org/freedesktop/timedate1");
}

int main() {
  get_proxy()
      ->callMethodAsync("SetNTP")
      .onInterface("org.freedesktop.timedate1")
      .withArguments(false, false)
      .uponReplyInvoke([](const sdbus::Error *error) {
        std::cout << "The callback is done!" << std::endl;
      });

  while (true) {
  }
  return 0;
}
```

What is the reason for this? Is this intended? What can I do to circumvent this problem?

**Comment by sangelovic** [comment] 2021-03-11 07:33
@hellow554 sorry for late reaction. Yes, this is behavior by design. The proxy you've created in `get_proxy()` will be invoked a D-Bus method upon, and right the call, just before `while` loop, the proxy will get deleted. It will get deleted because it has no name assigned to it in `main` function, hence it's a temporary object whose lifetime ends when all the side effects of line `get_proxy()->call...` are done. And, naturally, if a proxy goes down it means it's no more interested in signals and replies from async calls. All callbacks that were associated with a gone proxy a freed, too.

To solve the problem, simply keep the (named) instance variable of the proxy as long as you want to use it, e.g.:

```c++
int main(){
    auto proxy = get_proxy();
    proxy->callMethodAsync("SetNTP")...;
    while (true) {
    }
    return 0;
}
```

**Comment by hellow554** [comment] 2021-03-11 07:40
Thanks for the answer!

I thought so and in the meantime I used a background thread. I thought, because you have a callback `uponReplyInvoke` the proxy gets buffered somewhere in the background, but that's okay.

One more question: Should I create a new proxy for each method request or is it better to reuse the same proxy over and over again?
Currently my function `get_proxy` returns a new proxy every time. I wonder if I should switch to something like [`call_once`](https://en.cppreference.com/w/cpp/thread/call_once) and create a proxy there that I will use throught the entirety of my program.
I haven't really found anything in the docs yet (although they are very good, kudos to you for that!)

**Comment by sangelovic** [comment] 2021-03-11 07:57
Yes, the simplest approach is to create a proxy every time you're going to use it (to call a method on it), and then dispose of it. However, if you need to continuously listen to signals from the service, then you must keep it along. The decision to create a proxy on demand or create once and re-use it also depends on the trade-off of how often you make the calls (because creation of a proxy and its deletion is not trivial), etc.
If you make the calls frequently, especially async calls, then I'd just keep the proxy around and re-use it. It's more logical to me. The proxy class has been designed for re-use, even from multiple threads at the same time.
You don't necessarily need `call_once` if you create a proxy instance early in your application before you spawn threads that may be using it.

**Closed** 2021-03-11 07:58 UTC
