### ISSUE TITLE
add `virtual' to interface destructor for generated service/proxy adaptors

### ISSUE THREAD

**Issue by AndreyBarmaley** [Kistler-Group/sdbus-cpp#202] opened 2021-08-20 23:45 UTC
In an inherited class without a destructor, I get sigabrt:

```
 class MyProxy : public sdbus::ProxyInterface{}

std::unique_ptr<MyProxy> ptr; // <-- SIGABRT
```

**Comment by sangelovic** [comment] 2021-09-17 16:39
@AndreyBarmaley The code is not compilable. There is no `sdbus::ProxyInterface` class in sdbus-c++. Do you mean `sdbus::ProxyInterfaces` template class? In that case angle brackets with the list of proxy interfaces is missng.  Can you please be more specific and provide more description and full minimal example causing the abort?

**Comment by sangelovic** [comment] 2021-09-17 16:57
If the problem is addressed in #203 , then I'll close this issue, because #203 is not a solution...

**Closed** 2021-09-18 01:16 UTC
