### ISSUE TITLE
Allow using `std::tuple` instead of `sdbus::Struct`

### ISSUE THREAD

**Issue by hellow554** [Kistler-Group/sdbus-cpp#164] opened 2021-03-24 07:16 UTC
In fact `sdbus::Struct` is just a wrapper around `std::tuple`, yet I can't use `tuple` for message serialization or deserialization.

What is the exact reason that 

https://github.com/Kistler-Group/sdbus-cpp/blob/b190646aa528ebc78ba4d134ca31b32a9c4f1436/include/sdbus-c%2B%2B/TypeTraits.h#L241-L254

exists for `sdbus::Struct`, but not for `std::tuple`?

**Comment by sangelovic** [comment] 2021-03-24 08:57
That specialization does not exist by design. `Struct` template class has been designed to represent a D-Bus struct type. Not `std::tuple`. That `Struct` is implemented in terms of `std::tuple` (i.e., that it inherits from `std::tuple`) is more or less an *implementation detail*. It could have been defined completely on its own, but why, given that tuple provides all the API that also suits `Struct`. So we re-use the API, but have the advantage of a new type.

From the design POV, `Struct` is a more concrete, more expressive, stronger type than (quite generic) `std::tuple`. From the technical POV, `std::tuple` as a utility is simply used for different purposes in sdbus-c++. E.g., for clients to represent multiple return values of a function. And, for representing of a "collection" of function arguments in generic template implementations and handling that collection in a uniform aggregate way. Serialization and deserialization of `std::tuple` into a D-Bus message is supported, but it means and does a different thing from serializing/deserializing a `Struct`. It's a higher level implementation concept. It simply serializes/deserializes a "collection" of arguments (where one of these arguments can be a `Struct`), whereas serializing/deserializing a `Struct` means opening a container in a D-Bus message, writing to that container, etc.

**Comment by sangelovic** [comment] 2021-04-30 20:47
@hellow554 Have I answered your question? Can we close this issue?

**Closed** 2021-05-01 05:54 UTC
