### ISSUE TITLE
Async server implementation

### ISSUE THREAD

**Issue by Oberonc** [Kistler-Group/sdbus-cpp#9] opened 2018-04-26 11:18 UTC
Suppose a server operation doesnt take an insignificant amount of time and multiple clients attempt to get service.
The last ones will be starved or even timeout since right now handling is done one by one serially.
Can you provide an async replying mechanism ?

dbus-c++ had a relatively recent patch for that.

**Comment by Oberonc** [comment] 2018-05-01 09:18
Here is a preliminary patch that shows what I am interested in.
It basically changes the passed reply to a unique pointer of a Message.
This has 2 effects:
1. The user can choose when and where to call "reply->send();". This can be also done in a different thread.
2. The responsibility for calling "reply->send();" is passed to the user (in the low level API).

Your opinion about this patch ?

[sdbus-cpp-0.2.4.patch.txt](https://github.com/Kistler-Group/sdbus-cpp/files/1963397/sdbus-cpp-0.2.4.patch.txt)

**Comment by sangelovic** [comment] 2018-05-25 19:00
Hi, sorry for late reply, we've been very busy lately. I get your point and I'll look into that. As you write the async reply will have to be sent by the user, not the library. Internally, it will have to be sent back by the dispatcher thread, so there is some more synchronization involved. But that's not a problem. sdbus-c++ should abstract away those details on its API.  I'll keep you posted.

**Comment by sangelovic** [comment] 2018-05-25 19:03
Regarding the patch, I don't think we need to introduce exactly Ptr subtype here as dbus-c++ did it. The same is implemented in a simpler way here, I'd say. I'll let you know.

**Comment by Oberonc** [comment] 2018-06-12 09:54
Patch for low level API for version 0.2.5

[sdbus-cpp-0.2.5.patch.txt](https://github.com/Kistler-Group/sdbus-cpp/files/2093501/sdbus-cpp-0.2.5.patch.txt)

**Comment by Oberonc** [comment] 2018-06-14 19:13
Here is a patch that contains async code for low level API and convenience API
[sdbus-cpp-0.2.5.patch.txt](https://github.com/Kistler-Group/sdbus-cpp/files/2103673/sdbus-cpp-0.2.5.patch.txt)

The idea is to be able to use the convenience API like so:
_void concatenate(Message::Ptr reply, const std::vector<int> numbers, const std::string& separator) { .. }_
_concatenator->registerMethod("concatenate").onInterface(interfaceName).implementedAsAsync(&concatenate);_

I actually use this code right now in a daemon that accepts DB queries and pass them to a postgresql DB using thread pool (along with the reply object). Each query can take even up to a minute and more than one query needs to be handled at once.

**Comment by sangelovic** [comment] 2018-06-29 22:52
Hi,

there is a pending merge request to be merged soon that introduces support for asynchronous server-side methods. The changes there are roughly along the lines of your proposal (thank you!). Many additional details had to be addressed, like uniform API and type introspection for sync/async callbacks, asynchronous results communication, and thread safety (something that we've had big problems with in dbus-c++). Underlying sd-bus library is thread-aware but not thread-safe by design, so many operations (message receive/send operations especially) can only be done within the dispatcher thread. Sorry that it has taken that long. Feel free to provide feedback, and enjoy!

**Comment by Oberonc** [comment] 2018-07-11 19:40
Any idea when we'll have a stable release that contains these changes ? I would like to start working with it

**Comment by lukasdurfina** [comment] 2018-07-12 13:54
Hi Oberonc,
good note. Here it is: https://github.com/Kistler-Group/sdbus-cpp/releases/tag/v0.3.0

**Closed by lukasdurfina** 2018-07-12 13:54 UTC
