### ISSUE TITLE
why not using `std::string_view` in the interface instead of `std::string`

### ISSUE THREAD

**Issue by derived-coder** [Kistler-Group/sdbus-cpp#118] opened 2020-09-07 14:05 UTC
What do you think?

It is also possible to store just an string_view, but I am not 100% sure about it

**Comment by sangelovic** [comment] 2020-09-07 19:37
When sdbus-c++ was designed, there was only a limited set of C++17 features allowed to be used. But I am open for that change. It just needs an adequate analysis as to where in the API it makes sense to apply it. It may not make sense everywhere (for example, when `std::string` parameters are stored inside of an object, or when they are modified). Using `string_view` as a storage is dangerous, as we must make sure the "viewed" data exist so long as the view exists. Also, the change would be backwards incompatible, so I'd apply it only where it truly may provide added value. That said, if you'd volunteer to analyze and propose a change in a pull request, I'd volunteer to review and discuss, and potentially accept it ;)

**Comment by derived-coder** [comment] 2020-09-08 11:30
The question is, do you need to copy the data, are you modifying the strings somehere?

I am new to this library and what I see in the example I have, everybody i using "const char*" and then sdbus is copying the data.
When modifying the data, yeah, there it doesnt work to use "string_view".

**Comment by sangelovic** [comment] 2023-11-07 19:14
I looked into this in a greater detail now that we are close to releasing v2.0. In fact, `std::string_view` is pretty unusable in sdbus-c++ API. This is because of two reasons:

* some strings passed from outside into sdbus-c++ are stored inside sdbus-c++. Here, `std::string_view` as a parameter type would actually lead to constructing a `std::string` internally, which would make things even worse. Currently, we leverage move semantics for these strings, which greatly improves efficiency in some cases. These cases would get pessimized with `std::string_view`, leading to an always-copy behavior.
* and some (probably majority) of strings passed from outside into sdbus-c++ are further passed down to the underlying sd-bus library in the form of `const char*`. This renders `std::string_view` unusable for these cases, as `std::string_view` does not guarantee to provide us a null-terminated string.

In string-observing API functions, sdbus-c++ API takes these strings as a const-ref, maximizing efficiency by avoiding unnecessary copying. But -- sure -- if the client provides a `const char*` string as an argument, this leads to costly constructing and destructing a `std::string`. One solution here is that the client pre-constructs a `std::string` once and re-uses this one instead of `const char*`. The other solution, in case this is really desired, is that sdbus-c++ implements overloads of these functions that take `const char*` directly.

For now, I'm closing this issue as not planned since `std::string_view` is out of game. What remains in game is potential `const char*`-based overloads of string-observing sdbus-c++ API functions.

**Closed by sangelovic** 2023-11-07 19:14 UTC
Labels: good first issue

**Comment by sangelovic** [comment] 2024-04-18 18:03
For sdbus-c++ v2, `string_view` was introduced in the API where null-terminated string was not necessary (in commit https://github.com/Kistler-Group/sdbus-cpp/pull/364/commits/e7315eb9e4105e7bac17330020cc94bbf093afd8), and `const char*` overloads were introduced for efficiency in the API where a null-terminated string is expected (and anyway converted to const char*), in commit https://github.com/Kistler-Group/sdbus-cpp/pull/364/commits/011b36cc5003281343f8564fb119a481802c424b
