### ISSUE TITLE
std::terminate called by uncaught exceptions in Connection thread.

### ISSUE THREAD

**Issue by riuriuriu** [Kistler-Group/sdbus-cpp#74] opened 2019-09-16 13:05 UTC
Hi Stano, I hope you are doing well.

There's a bug where [Connection::enterProcessingLoop()](https://github.com/Kistler-Group/sdbus-cpp/blob/8dea11bac682456cc1e3c861c9415b1082e4f829/src/Connection.cpp#L85) calls methods which might throw. Exceptions are never caught by this thread which causes it to die -> call std::terminate on the process.

For instance, [Connection::processPendingRequest()](https://github.com/Kistler-Group/sdbus-cpp/blob/8dea11bac682456cc1e3c861c9415b1082e4f829/src/Connection.cpp#L328) throws if `iface_->sd_busProcess(...)` returns an error. 

In this case, terminate() is called since there is no try/catch in the thread function.

I could help fixing this but I currently don't know how this lib intends to gracefully handle this situation. Do you want to transport the exception to the caller thread?

**Comment by sangelovic** [comment] 2019-09-23 06:59
Hi Urs,

There are 2 types of D-Bus related errors that can occur (see https://github.com/Kistler-Group/sdbus-cpp/blob/master/docs/using-sdbus-c%2B%2B.md#error-signalling-and-propagation):

* Error on the application level. This is to be handled by the application. For example, the callee fails to execute a method and the caller should react to the exception that represents the failure. sdbus-cpp gracefully delivers this exception to the application, and is not affected by this exception.

* Error in D-Bus library or D-Bus daemon itself (e.g. sd_bus_process fails, socket is not allocated, etc.). This is serious error, and when we get this error, it usually means the application is in big troubles in general. For example, there is lack of resources. Or it can by any other OS-related error. Here, there is no way for sdbus-cpp to tell what to do, the reaction should be defined by higher layers, so sdbus-cpp just backs off and throws exception to be handled by the application. 

There is (by design) no built-in logic to transfer such exceptions between threads. Yes, we could think of propagating the ecxeption upon joining. But, typically, D-Bus event loop threads are long-running and if one fails hard (which means application has big problems anyway), then this thread would silently stop, waiting to be joined (which might happen very late from now) to propagate the ecxeption. There are other ways of transferring exceptions between threads, but are more complex (and questions arise as which thread is gonna be the collecting thread etc.).

This problem clearly belongs to a higher layer of abstraction, so instead of that, sdbus-cpp provides freedom of choice. If application wants to react gracefully to all such hard errors, it should run the event loop in thread managed by the application (this is mostly the case of services you have). The application just wraps the call in try-catch. If the application doesn't care, it can use the simpler approach of threads managed internally by sdbus-cpp (e.g., enterProcessingLoopAsync), but with the cost of losing chance to gracefully handle its hard exceptions.

Now, there are two specifics related to the GetMachineId problem in integration tests that you referenced:

* This is IMO typical application error. The server cannot find out and return the ID because the file is missing. It should return error and this single test would fail, but the application would continue. But GetMachineId is implemented by libsystemd and when I looked at it, I saw that instead of returning error reply, it causes server-side event loop to fail hard (hence that crash message). This is the main problem here. I think this is not correct, and I will ping systemd guys about it.

* Second, the server-side event loop in integration tests is invoked by calling enterProcessingLoopAsync, which means we gave up control over hard exceptions there (we are just tests and it's ok).

Does it make sense to you?

**Comment by riuriuriu** [comment] 2019-09-23 07:55
> If application wants to react gracefully to all such hard errors, it should run the event loop in thread managed by the application (this is mostly the case of services you have).

Ah, I didn't know that's the "standard" case and I can see that our applications really manage their own event loop. So that's good news.

> I think this is not correct, and I will ping systemd guys about it.

Makes sense.

> which means we gave up control over hard exceptions there (we are just tests and it's ok)

I would argue that it's never ok for a library to terminate the application. But I agree that in this case it's rather an issue with libsystemd handling an application error as "hard bus error".

**Comment by sangelovic** [comment] 2019-09-23 08:34
> I would argue that it's never ok for a library to terminate the application. 

Fully agree, and this is not the case of sdbus-cpp. It doesn't invoke std::terminate (which would be totally wrong). It's just a source of an exception which is not handled by anybody, so C++ runtime catches it and it is C++ runtime that by default invokes std::terminate in that case. In some applications it may be a normal error handling strategy that they crash loudly on an unexpected "fatal" error, because anything might just be useless.

**Comment by sangelovic** [comment] 2019-10-06 08:40
Hey Urs, you can close the issue if it's OK for you.

**Closed** 2019-10-07 07:21 UTC

**Comment by riuriuriu** [comment] 2019-10-07 07:36
Adding discussion with systemd guys for reference:

https://lists.freedesktop.org/archives/systemd-devel/2019-September/043497.html.
